[package]
name = "rust-snake"
version = "0.1.0"
authors = ["ravi0the0sun <punravi73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
